using System;
using System.IO;
using System.Text;
using Godot;
using PVZHE.ModEditor.Blueprint;

namespace PVZHE.ModEditor.ScriptEditor;

public static class XWBlueprintGeneratedCSharpPolicy
{
	public enum LinkState
	{
		NotGenerated,
		Orphaned,
		Linked
	}

	public const string GeneratedHeader = "// <auto-generated by PVZHE ModEditor Blueprint>";

	public const string SourceHeaderPrefix = "// pvzhe-blueprint-link-v1: ";

	private const int MetadataLineLimit = 8;

	public static string AttachMetadata(string code, string blueprintSourcePath, string generatedScriptPath)
	{
		if (code == null)
		{
			code = "";
		}
		code = StripExistingMetadata(code);
		string s = BuildStoredSourcePath(blueprintSourcePath, generatedScriptPath);
		string value = Convert.ToBase64String(Encoding.UTF8.GetBytes(s));
		return $"{"// <auto-generated by PVZHE ModEditor Blueprint>"}\n{"// pvzhe-blueprint-link-v1: "}{value}\n" + code.TrimStart('\ufeff');
	}

	public static bool IsGeneratedSource(string source)
	{
		if (string.IsNullOrEmpty(source))
		{
			return false;
		}
		using StringReader stringReader = new StringReader(source);
		for (int i = 0; i < 8; i++)
		{
			string text = stringReader.ReadLine();
			if (text == null)
			{
				break;
			}
			if (string.Equals(text.Trim(), "// <auto-generated by PVZHE ModEditor Blueprint>", StringComparison.Ordinal))
			{
				return true;
			}
		}
		return false;
	}

	public static bool TryReadBlueprintSource(string source, out string blueprintSourcePath)
	{
		blueprintSourcePath = "";
		if (!IsGeneratedSource(source))
		{
			return false;
		}
		using StringReader stringReader = new StringReader(source);
		for (int i = 0; i < 8; i++)
		{
			string text = stringReader.ReadLine();
			if (text == null)
			{
				break;
			}
			text = text.Trim();
			if (!text.StartsWith("// pvzhe-blueprint-link-v1: ", StringComparison.Ordinal))
			{
				continue;
			}
			string s = text.Substring("// pvzhe-blueprint-link-v1: ".Length).Trim();
			try
			{
				string path = Encoding.UTF8.GetString(Convert.FromBase64String(s));
				path = NormalizeStoredPath(path);
				if (!IsBlueprintResourcePath(path))
				{
					return false;
				}
				blueprintSourcePath = path;
				return true;
			}
			catch (FormatException)
			{
				return false;
			}
		}
		return false;
	}

	public static bool TryResolveTrustedBlueprintSource(string generatedScriptPath, string source, string activeProjectRoot, out string blueprintSourcePath)
	{
		return GetLinkState(generatedScriptPath, source, activeProjectRoot, out blueprintSourcePath) == LinkState.Linked;
	}

	public static LinkState GetLinkState(string generatedScriptPath, string source, string activeProjectRoot, out string blueprintSourcePath)
	{
		blueprintSourcePath = "";
		if (!IsGeneratedSource(source))
		{
			return LinkState.NotGenerated;
		}
		if (!TryReadBlueprintSource(source, out var blueprintSourcePath2))
		{
			return LinkState.Orphaned;
		}
		if (Path.IsPathRooted(blueprintSourcePath2) || blueprintSourcePath2.StartsWith("res://", StringComparison.OrdinalIgnoreCase) || blueprintSourcePath2.StartsWith("user://", StringComparison.OrdinalIgnoreCase) || blueprintSourcePath2.IndexOfAny(new char[2] { '/', '\\' }) >= 0)
		{
			return LinkState.Orphaned;
		}
		string text = ToAbsolutePath(generatedScriptPath);
		string text2 = ToAbsolutePath(activeProjectRoot);
		if (string.IsNullOrWhiteSpace(text) || string.IsNullOrWhiteSpace(text2))
		{
			return LinkState.Orphaned;
		}
		string text3 = ToAbsolutePath(Path.Combine(Path.GetDirectoryName(text) ?? "", blueprintSourcePath2));
		if (string.IsNullOrWhiteSpace(text3) || !IsInsideRoot(text, text2) || !IsInsideRoot(text3, text2) || !IsSafePath(text, text2) || !IsSafePath(text3, text2))
		{
			return LinkState.Orphaned;
		}
		string path = Path.Combine(Path.GetDirectoryName(text3) ?? "", Path.GetFileNameWithoutExtension(text3) + ".generated.cs");
		if (!string.Equals(Path.GetFullPath(text), Path.GetFullPath(path), StringComparison.OrdinalIgnoreCase))
		{
			return LinkState.Orphaned;
		}
		if (!File.Exists(text3))
		{
			return LinkState.Orphaned;
		}
		if (!GodotObject.IsInstanceValid(ResourceLoader.Load<XWBPScript>(text3, "", ResourceLoader.CacheMode.Ignore)))
		{
			return LinkState.Orphaned;
		}
		blueprintSourcePath = text3.Replace('\\', '/');
		return LinkState.Linked;
	}

	private static bool IsBlueprintResourcePath(string path)
	{
		string extension = path.GetExtension();
		if (!string.Equals(extension, "tres", StringComparison.OrdinalIgnoreCase))
		{
			return string.Equals(extension, "res", StringComparison.OrdinalIgnoreCase);
		}
		return true;
	}

	private static string NormalizeStoredPath(string path)
	{
		return (path ?? "").Trim().Replace('\\', '/');
	}

	private static string BuildStoredSourcePath(string blueprintSourcePath, string generatedScriptPath)
	{
		string text = ToAbsolutePath(blueprintSourcePath);
		string text2 = ToAbsolutePath(generatedScriptPath);
		if (!string.IsNullOrWhiteSpace(text) && !string.IsNullOrWhiteSpace(text2) && string.Equals(Path.GetDirectoryName(text), Path.GetDirectoryName(text2), StringComparison.OrdinalIgnoreCase))
		{
			return Path.GetFileName(text);
		}
		return NormalizeStoredPath(blueprintSourcePath);
	}

	private static string StripExistingMetadata(string source)
	{
		if (!IsGeneratedSource(source))
		{
			return source ?? "";
		}
		using StringReader stringReader = new StringReader(source ?? "");
		StringBuilder stringBuilder = new StringBuilder();
		int num = 0;
		string text;
		while ((text = stringReader.ReadLine()) != null)
		{
			if (num >= 8 || (!string.Equals(text.Trim(), "// <auto-generated by PVZHE ModEditor Blueprint>", StringComparison.Ordinal) && !text.Trim().StartsWith("// pvzhe-blueprint-link-v1: ", StringComparison.Ordinal)))
			{
				stringBuilder.AppendLine(text);
			}
			num++;
		}
		return stringBuilder.ToString().TrimStart('\r', '\n');
	}

	private static string ToAbsolutePath(string path)
	{
		if (string.IsNullOrWhiteSpace(path))
		{
			return "";
		}
		try
		{
			string text = NormalizeStoredPath(path);
			if (text.StartsWith("res://", StringComparison.OrdinalIgnoreCase) || text.StartsWith("user://", StringComparison.OrdinalIgnoreCase))
			{
				text = ProjectSettings.GlobalizePath(text);
			}
			return Path.GetFullPath(text);
		}
		catch
		{
			return "";
		}
	}

	private static bool IsInsideRoot(string path, string root)
	{
		try
		{
			string value = Path.GetFullPath(root).TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar) + Path.DirectorySeparatorChar;
			return Path.GetFullPath(path).StartsWith(value, StringComparison.OrdinalIgnoreCase);
		}
		catch
		{
			return false;
		}
	}

	private static bool IsSafePath(string path, string root)
	{
		try
		{
			string text = Path.GetFullPath(root).TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
			string fullPath = Path.GetFullPath(path);
			string relativePath = Path.GetRelativePath(text, fullPath);
			if (relativePath.StartsWith("..", StringComparison.Ordinal) || Path.IsPathRooted(relativePath))
			{
				return false;
			}
			string text2 = text;
			if (HasReparsePoint(text2))
			{
				return false;
			}
			string[] array = relativePath.Split(new char[2]
			{
				Path.DirectorySeparatorChar,
				Path.AltDirectorySeparatorChar
			}, StringSplitOptions.RemoveEmptyEntries);
			foreach (string path2 in array)
			{
				text2 = Path.Combine(text2, path2);
				if ((Directory.Exists(text2) || File.Exists(text2)) && HasReparsePoint(text2))
				{
					return false;
				}
			}
			return true;
		}
		catch
		{
			return false;
		}
	}

	private static bool HasReparsePoint(string path)
	{
		try
		{
			return (File.GetAttributes(path) & FileAttributes.ReparsePoint) != 0;
		}
		catch
		{
			return true;
		}
	}
}
